### ISSUE TITLE
"OverflowR6V2"

### ISSUE THREAD

**Issue by shaiiko** [NMan1/OverflowR6V2#10]
Hello, i linked  OverflowR6Rust.sln to the Right path \OverflowR6V2\OverflowR6V2.vcxproj when i open the project it says "unloaded" OverflowR6V2 have you any idea how to fix the problem if i rename OverflowR6V2 to smth like "OverflowR6V22" it will load but give me Errors when i try to run the cheat

**Comment by NMan1** [comment]
You've opened 3 issues throughout my projects, its clear you have no idea what your doing. Please stop wasting my time.
