### ISSUE TITLE
[!] failed to aquire base address...

### ISSUE THREAD

**Issue by MMXMMC** [NMan1/OverflowR6V2#11]
It says it in the title, what could I do about it?

**Comment by NMan1** [comment]
Did you load the driver?

**Comment by MMXMMC** [comment]
Yes I did

**Comment by NMan1** [comment]
Look at the drivers output with dbgview

**Comment by MMXMMC** [comment]
![gfh](https://user-images.githubusercontent.com/67609790/86059793-c3ef7400-ba63-11ea-9258-9948f4108193.png)
I somehow can't view the output.

**Comment by MMCMMX** [comment]
![Unbenannt](https://user-images.githubusercontent.com/67714373/86294692-5ffcb500-bbf5-11ea-99b5-33c944af5b41.PNG)

**Comment by MMCMMX** [comment]
Still same Error 🥇

**Comment by NMan1** [comment]
Thats not even this driver? What.....
