### ISSUE TITLE
Driver Issue + failed to aquire base address.

### ISSUE THREAD

**Issue by MMCMMX** [NMan1/OverflowR6V2#12]
[<] Loading vulnerable driver
[+] 10.0.18362.900
[+] Image base has been allocated at 0xFFFF810F3F9F2000
[<] Calling DriverEntry 0xFFFF810F3F9F46B0
[+] 10.0.18362.900
[+] DriverEntry returned 0x00000000
[<] Unloading vulnerable driver
 [+] success

Driver Output after load

**Comment by NMan1** [comment]
Quit spamming me with issues! You have no idea what your doing, quit wasting my time!

**Comment by MMCMMX** [comment]
Because you make shit explain fdp

**Comment by NMan1** [comment]
I help people who have a brain, you are not one of those people.
