### ISSUE TITLE
Help compiling(Noob warning)

### ISSUE THREAD

**Issue by NotReallyConnor** [NMan1/OverflowR6V2#17]
So I'm going to make it clear from the get-go that I am a total noob when it comes to how to use Visual  Studio and generally do any of this, So pardon me for every mistake I make and every dumb thing I do.

To compile it you say to change the directories to where the files are, so here are my idiotic questions regarding this
1. Do you mean the files for R6S or the downloaded files
2. At what line do you want those changes? Only places I see directories in is the 3 Project and endproject lines and modifying those just gave out to me despite me pointing to where the vcxproj files where.

When the files are left untouched and I just trying to open them I get 2 errors:
warning  : The build tools for WindowsKernelModeDriver10.0 cannot be found. Install WindowsKernelModeDriver10.0 to build using the WindowsKernelModeDriver10.0 build tools.
I am guessing that's because WDK is not installed, which I am downloading rn but my slow internet will take a while

warning  : Platform 'ARM64' referenced in the project file 'OverflowDriver' cannot be found.
Yeah I have no clue for this one, Guessing it's because of the earlier error but no clue.

Sorry for being such a newbie but hope I can get some help

**Comment by NMan1** [comment]
Change the directories in the vcxproj and the sln files to what matches your disk. This is very outdated so I wouldn’t bother using it for anything other than a learning source as it’s not gonna work when run.

**Comment by NotReallyConnor** [comment]
Ah I see, thanks for the help
