### ISSUE TITLE
KMODE_EXCEPTION_NOT_HANDLED when launching OverflowR6V2.exe

### ISSUE THREAD

**Issue by takeame** [NMan1/OverflowR6V2#2]
The driver loaded successfully with my own mapper, but the moment I launch OverflowR6V2.exe, it gives BSOD with KMODE_EXCEPTION_NOT_HANDLED.

Any help would be greatly appreciated!

**Comment by takeame** [comment]
> Replace the kernel memory struct with the usermode one and In the get proc id method assign the passed string to the memory structs process name string.
> 

Hi, i replaced the usermode memory struct with the kernel one instead because its the usermode that lacks const char* process_name;
doing otherwise gives me a ton of errors.
I assigned the passed string to the memory structs process name string too 

however, launching the program still gives bsod

**Comment by takeame** [comment]
> > > same here i would like to know if it's possible to get procid by Windowname , since the game im trying to use this on has a child process
> > 
> > 
> > whats ur discord, wanna ask something
> 
> its Z4bb3er#5502

Hi, I wanna ask something too, I've sent u a friend request, my username is surprise on discord

**Comment by NMan1** [comment]
You didn’t do it correctly. It’s the other way around. I explained how to do it in detail, this is very simple. If you cannot do this I don’t think you should be anywhere near the kernel. Your just going to cause yourself more issues. Learn the basics first.
