### ISSUE TITLE
I can't compose on the window

### ISSUE THREAD

**Issue by felki12** [NMan1/OverflowR6V2#4]
[+] aquired base address and PID: 7ff73b0a0000
[+] found hijackwindow: 00000000000202B0
[+] hijacking window...
        [+] d3d11 device : 0x0000027004F47F18
        [+] dxgi device : 0x0000027004F47728
        [+] dxgi factory : 0x000002700B8055D0
        [+] dxgi swap chain : 0x000002700B6A21A0
        [+] d2d1 factory : 0x00000270047BB740
        [+] d2d1 device : 0x00000270047F6810
        [+] d2d1 context : 0x00000270047F83E0
        [+] dxgi surface : 0x0000027004EDCFE0
        [+] d2d1 bitmap : 0x00000270047F9230
        [+] d2d1 brush : 0x0000027003FA8820
        [+] local window thread: 0xCCCCCCCCCCCCCCCC
        [+] remote window thread: 0xCCCCCCCCCCCCCCCC
        [+] composing on window...
        [+] target window found: 00000000000202B0

Seems like I am able to get everything but i can't swap the windows threads in order to compose? do you have any idea why? Also I am using Nvidia Share to compose!

**Comment by NMan1** [comment]
Well it’s something to do with the driver probably so your going to have to debug it.

**Comment by felki12** [comment]
When I compiled as release, I can get some normal thread address, but, both the local and the remote thread are the same. I think i will have to debug it too.

**Comment by felki12** [comment]
"ValidateHwnd call failed (get)" here is the problem, do u have any guess why? cause i think i am passing the right parameter to the hook call and the driver seems not to be able to receive the hwnd in order to use validatehwnd

**Comment by NMan1** [comment]
1. The address of ValidateHwnd is probably wrong somehow
2. Print the hwnd from usermode and see if it matches the drivers one

**Comment by felki12** [comment]
Fixed. Somehow the driver was getting the wrong hwnd from the hook. So far so good. Thx for the help and for your time.
