### ISSUE TITLE
[!] failed to aquire base address...

### ISSUE THREAD

**Issue by AmonKing** [NMan1/OverflowR6V2#6]
I don't seem to have done anything wrong, WinVer1903.
Do I need to load the driver？ use kdmapper？

**Comment by NMan1** [comment]
What? Do you need to load the driver? Of you course you need to load the driver, is it just going to magically appear into memory?

**Comment by AmonKing** [comment]
Ok I see. Forgive me for asking this Noob question.   Thank you for your answer.
