### ISSUE TITLE
Cheat not loading

### ISSUE THREAD

**Issue by mixmax0M** [NMan1/OverflowR6V2#9]
Hey, I would like to ask why "OverflowR6V2.vcxproj" doesn't load even with the right path, and why I can't find "OverflowRust.vcxproj" in the folder. 

Best regards.

**Comment by NMan1** [comment]
OverflowRust isnt there because I removed it from this project, this is for r6

**Comment by NMan1** [comment]
It will load if you did it correctly, so you must've done something wrong. Google is your best friend,

**Comment by mixmax0M** [comment]
OK thanks for helping me.
